[package]
name = "pnc"
version = "0.1.0"
authors = ["Michael Budde <mbudde@gmail.com>"]

[dependencies]
shlex = "0.1"
log = "0.3"
env_logger = "0.4"
clap = "2.2.2"
error-chain = "0.11"
num = "0.1.40"
